export const t = {
  bgPrimary:     'var(--bg-primary)',
  bgCard:        'var(--bg-card)',
  bgInput:       'var(--bg-input)',
  border:        'var(--border)',
  borderInput:   'var(--border-input)',
  textPrimary:   'var(--text-primary)',
  textSecondary: 'var(--text-secondary)',
  textMuted:     'var(--text-muted)',
  accent:        'var(--accent)',
  accent2:       'var(--accent-2)',
  accentBg:      'var(--accent-bg)',
  accentBorder:  'var(--accent-border)',
  accentText:    'var(--accent-text)',
  greenBg:       'var(--green-bg)',
  greenBorder:   'var(--green-border)',
  greenText:     'var(--green-text)',
  tagBg:         'var(--tag-bg)',
  pillBg:        'var(--pill-bg)',
  pillBorder:    'var(--pill-border)',
  pillText:      'var(--pill-text)',
  yellowBg:      'var(--yellow-bg)',
  yellowBorder:  'var(--yellow-border)',
  yellowText:    'var(--yellow-text)',
  heroGlow:      'var(--hero-glow)',
  navbarBg:      'var(--navbar-bg)',
  navbarBorder:  'var(--navbar-border)',
};